# Generated by Django 5.2.8 on 2026-06-17 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_knowledge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('practical_exposure', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('communication_skills', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diary_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_viva_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(choices=[('marks_entered', 'Marks Entered'), ('marks_updated', 'Marks Updated'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
