# Generated by Django 6.0.6 on 2026-06-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_type', models.CharField(choices=[('regular', 'Regular Internship'), ('assessment', 'Assessment Internship'), ('additional', 'Additional Internship'), ('repeated', 'Repeated Internship')], default='regular', max_length=20)),
                ('internship_number', models.CharField(max_length=20)),
                ('related_semester', models.CharField(blank=True, max_length=50)),
                ('academic_phase', models.CharField(blank=True, max_length=50)),
                ('reporting_officer_name', models.CharField(blank=True, max_length=100)),
                ('reporting_officer_contact', models.CharField(blank=True, max_length=20)),
                ('reporting_officer_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('nature_of_work', models.TextField(blank=True)),
                ('stipend_received', models.BooleanField(default=False, verbose_name='Stipend Received')),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student_remarks', models.TextField(blank=True, verbose_name='Student Experience / Remarks')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='internship_certificates/')),
                ('report', models.FileField(blank=True, null=True, upload_to='internship_reports/')),
                ('completion_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_completed', 'Not Completed'), ('repeated', 'Repeated')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_correction', 'Needs Correction'), ('verified', 'Verified'), ('marks_entered', 'Marks Entered'), ('approved', 'Approved'), ('locked', 'Locked'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_remarks', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internship_records', to='organisations.organisation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_records', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'internship_number'],
            },
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('assignment_level', models.CharField(choices=[('programme', 'Programme'), ('batch', 'Batch'), ('student', 'Student'), ('internship', 'Internship-Specific')], default='student', max_length=20)),
                ('related_semester', models.CharField(blank=True, max_length=50)),
                ('reason_for_change', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentors', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.internshiprecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='students.student')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
