# Generated by Django 5.2.8 on 2026-06-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprecord',
            name='reporting_officer_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='reporting_officer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='reporting_officer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='internshiprecord',
            name='stipend',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
