# Generated by Django 5.2.8 on 2026-06-17 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_type', models.CharField(choices=[('regular_1', 'Regular Internship 1'), ('regular_2', 'Regular Internship 2'), ('regular_3', 'Regular Internship 3'), ('regular_4', 'Regular Internship 4'), ('regular_5', 'Regular Internship 5'), ('regular_6', 'Regular Internship 6'), ('regular_7', 'Regular Internship 7'), ('regular_8', 'Regular Internship 8'), ('assessment', 'Assessment Internship')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('verifying', 'Pending Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='planned', max_length=20)),
                ('mentor_at_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='organisations.organisation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'internship_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reflection_summary', models.TextField()),
                ('faculty_remarks', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='internships.internship')),
            ],
        ),
    ]
