# Generated by Django 5.2.8 on 2026-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='hod_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
