# Generated by Django 5.2.14 on 2026-06-15 11:23

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('department_admin', 'Department Admin'), ('faculty_mentor', 'Faculty Mentor'), ('evaluator', 'Evaluator'), ('hod', 'HoD'), ('student', 'Student')], db_index=True, max_length=32, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['department'], name='accounts_us_departm_4298b0_idx')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
