# Generated by Django 6.0.6 on 2026-06-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=30)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksheet_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('viva_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ppo_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evaluated_at', models.DateField(blank=True, null=True)),
                ('evaluator_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('coordinator_remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_approved', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internship Marks',
                'verbose_name_plural': 'Internship Marks',
                'ordering': ['internship_record'],
            },
        ),
    ]
