# Generated by Django 6.0.6 on 2026-06-19 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('intermediate', 'Intermediate Assessment'), ('report', 'Report Evaluation'), ('presentation', 'Presentation / Review'), ('mentor', 'Mentor Evaluation'), ('viva', 'Final Viva'), ('other', 'Other')], max_length=20)),
                ('assessment_name', models.CharField(max_length=100)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('internship_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='internships.internshiprecord')),
            ],
            options={
                'ordering': ['internship_record', 'assessment_type'],
            },
        ),
        migrations.CreateModel(
            name='MarkEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='assessments.assessmentmark')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
