# Generated by Django 5.2.8 on 2026-06-29 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('internships', '0002_internshiprecord_reporting_officer_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentmark',
            options={'ordering': ['internship_record']},
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='assessment_name',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='marks_awarded',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='maximum_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='weightage',
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='certificate_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='classification',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='ppo_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='viva_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='worksheet_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_evaluated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='internship_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mark', to='internships.internshiprecord'),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=15),
        ),
    ]
