# Generated by Django 6.0.6 on 2026-06-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipmarks',
            name='internship_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='internships.internshiprecord'),
        ),
        migrations.AddField(
            model_name='markedithistory',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markedithistory',
            name='marks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='assessments.internshipmarks'),
        ),
    ]
