# Generated by Django 5.2.8 on 2026-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('faculty_coordinator', 'Faculty Coordinator'), ('faculty_evaluator', 'Faculty Evaluator'), ('student', 'Student')], default='student', max_length=30),
        ),
    ]
