# Generated by Django 5.2.8 on 2026-06-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('law_firm', 'Law Firm'), ('advocate', 'Individual Advocate'), ('ngo', 'NGO'), ('corporate', 'Corporate Legal Cell'), ('court', 'Court/Judiciary')], max_length=20)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_council_id', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_details', to='organisations.organisation')),
            ],
        ),
    ]
